### PR TITLE
feat: creating custom help string

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**
With the migration to OCLIF, our previous help has been updated, so this PR aims to restore the help string as before, 

> Though functionally the OCLIF's help string out of the box is very helpful, So should we update this, or use what OCLIF supports out of the box. Maybe we could have some color-coding different sections.  Any opinion @derberg @fmvilas @magicmatatjahu 

Oclif's help strings: 
```
All in one CLI for all AsyncAPI tools

VERSION
  @asyncapi/cli/0.6.3 linux-x64 node-v16.13.0

USAGE
  $ asyncapi [COMMAND]

TOPICS
  config  access configs

COMMANDS
  config    access configs
  help      display help for asyncapi
  validate  validate asyncapi file
```

### CODE REVIEW

**Comment by Souvikns** [comment]
ready to be reviewed 🤞🏻

**Review by fmvilas — APPROVED** [review]
:shipit:

**Comment by fmvilas** [comment]
@Souvikns you need to resolve some conflicts with the `master` branch but other than that it looks great to me 🙌

**Comment by Souvikns** [comment]
@fmvilas  I think I need another approval.

**Review by fmvilas — APPROVED** [review]

**Comment by fmvilas** [comment]
@Souvikns CLI is broken again 😅 I get this error this time:

```
$ asyncapi --help
    Error: Unable to load configured help class "./src/help/index.ts", failed with message:
    Cannot find module '/Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/src/help/index.ts'
    Require stack:
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/@oclif/plugin-help/lib/u
    til.js
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/@oclif/plugin-help/lib/c
    ommand.js
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/@oclif/plugin-help/lib/i
    ndex.js
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/@oclif/command/lib/comma
    nd.js
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/node_modules/@oclif/command/lib/index
    .js
    - /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/@asyncapi/cli/bin/run
```

**Comment by fmvilas** [comment]
I think you have to change [this line](https://github.com/asyncapi/cli/blob/master/package.json#L80) to:

```
"helpClass": "./lib/help"
```

This is what I see when I look into the installed module:

```
$ ll /Users/fmvilas/.nvm/versions/node/v14.15.1/lib/node_modules/\@asyncapi/cli/lib/help
total 32
drwxr-xr-x   6 fmvilas  staff   192B  3 nov 08:48 .
drwxr-xr-x  10 fmvilas  staff   320B  3 nov 08:48 ..
-rw-r--r--   1 fmvilas  staff   219B 26 oct  1985 command.d.ts
-rw-r--r--   1 fmvilas  staff   2,2K 26 oct  1985 command.js
-rw-r--r--   1 fmvilas  staff   305B 26 oct  1985 index.d.ts
-rw-r--r--   1 fmvilas  staff   1,8K 26 oct  1985 index.js
```

**Pull request merged**
