### PR TITLE
docs: added short description for pretty command

### LINKED ISSUE #1577: [📑 Docs]: Update the documentation about the pretty command in the CLI
### What Dev Docs changes are you proposing?

After introducing the https://github.com/asyncapi/cli/pull/1549 new command that is asyncapi format the docs has not updated need to update the docs to understand more better about the command usage.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by SahilDahekar**
**Description**

- Added short description for pretty command.

**Related issue(s)**

Resolves #1577

### CODE REVIEW

**Comment by SahilDahekar** [comment]
Should i create a seperate PR to add these doc changes to website ?

**Comment by AayushSaini101** [comment]
> Should i create a seperate PR to add these doc changes to website ?

@SahilDahekar Kindly update the doc in this PR as well

**Comment by SahilDahekar** [comment]
> > Should i create a seperate PR to add these doc changes to website ?
> 
> @SahilDahekar Kindly update the doc in this PR as well

**Comment by AayushSaini101** [comment]
LGTM @SahilDahekar

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
