### PR TITLE
fix: update @asyncapi/bundler to 0.5.0 version

### PR DESCRIPTION
**Pull request by aeworxet**
This PR:
- Updates package `@asyncapi/bundler` to `0.5.0` version
- Makes the behavior of the CLI's `asyncapi bundle` command consistent with the standalone `Bundler` application and its [`README.md`](https://github.com/asyncapi/bundler/blob/master/README.md)
- Updates tests and test YAMLs

`>` writes to the resulting YAML the full contents of `stdout`, which now contains more than just the pure contents of the output YAML, thereby polluting the specified YAML. Therefore `>` is no longer listed as an additional output option in the help.

### CODE REVIEW

**Comment by aeworxet** [comment]
Pinging @Amzani for https://github.com/asyncapi/cli/pull/1200 / https://github.com/asyncapi/cli/pull/1228 and @francocm for https://github.com/asyncapi/cli/pull/1389 so they are aware of this mandatory PR.

#

Should fix https://github.com/asyncapi/cli/issues/1323 by @mfroberg
<details>
<summary>↓</summary>

CLI's `bundle` command with `Bundler` of version `0.5.0`:
```
asyncapi bundle main.yaml -o asyncapi.yaml
```
↓
```
asyncapi: 3.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  userSignedUp:
    address: user/signedup
    messages:
      UserSignedUp:
        payload:
          type: object
          properties:
            displayName:
              type: string
              description: Name of the user
            email:
              type: string
              format: email
              description: Email of the user
operations:
  onUserSignUp:
    action: receive
    channel:
      $ref: '#/channels/userSignedUp'
    messages:
      - $ref: '#/channels/userSignedUp/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user

```

↓

Standalone `Optimizer` of version `1.0.2`:
```
const optimizedDocument = optimizer.getOptimizedDocument({
  output: 'YAML',
  rules: {
    reuseComponents: true,
    removeComponents: true,
    moveAllToComponents: true,
    moveDuplicatesToComponents: false,
  },
  disableOptimizationFor: {
    schema: true,
  },
})
```
↓
```
asyncapi: 3.0.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  userSignedUp:
    address: user/signedup
    messages:
      UserSignedUp:
        $ref: '#/components/messages/UserSignedUp'
operations:
  onUserSignUp:
    action: receive
    channel:
      $ref: '#/channels/userSignedUp'
    messages:
      - $ref: '#/channels/userSignedUp/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user
```
</details>

**Review by Souvikns — APPROVED** [review]
LGTM

**Review by Shurtu-gal — APPROVED** [review]
LGTM 🚀

**Review by Amzani — APPROVED** [review]
LGTM

**Pull request merged**
