### PR TITLE
feat: diff will show error on breaking changes

### PR DESCRIPTION
**Pull request by aayushmau5**
**Description**

`diff` command will now show error(with exit code 1) when breaking changes are detected. This is the default behaviour.
There's also a flag `--no-error` you can provide to not show this error.
Ex.
```
diff ./old.yml ./new.yml --no-error
```

The current behaviour is that diff will show error no matter the `type` of changes required. For example, 
```
diff ./old.yml ./new.yml --type=non-breaking
```
will show a breaking change error in case there are breaking changes detected between provided documents. 

**Related issue(s)**

None

### CODE REVIEW

**Comment by aayushmau5** [comment]
cc @jfcote You can try out the changes.

**Review by JFCote — APPROVED** [review]
LGTM!

**Review by Souvikns — APPROVED** [review]

**Comment by aayushmau5** [comment]
@Souvikns when can we merge this?

**Pull request merged**
