### PR TITLE
feat: upgrade optimizer

### PR DESCRIPTION
**Pull request by KhudaDad414**
**Description**
- Upgrade asyncapi/optimizer to v1

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
Should the `usage.md` be updated or we let an automated PR do it?

**Comment by peter-rr** [comment]
> Should the `usage.md` be updated or we let an automated PR do it?

I think the document is updated automatically, at least from my previous experience with other commands 😄

**Review by peter-rr — APPROVED** [review]
LGTM 🚀

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
