### PR TITLE
fix: update @asyncapi/optimizer to 1.0.3 version and others

### PR DESCRIPTION
**Pull request by aeworxet**
This PR is a clone of https://github.com/asyncapi/cli/pull/1503 created just to pass the frozen automerge mechanism.

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
I suppose workflow is not able to setup a clean install properly @aeworxet.

**Comment by aeworxet** [comment]
```bash
Error: node_modules/@types/lodash/common/object.d.ts(1026,46): error TS1005: '?' expected.
Error: node_modules/@types/lodash/common/object.d.ts(1031,46): error TS1005: '?' expected.
Error: node_modules/@types/lodash/common/object.d.ts(1041,46): error TS1005: '?' expected.
```
is due to this issue
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/69932

I changed

```diff
-    "typescript": "4.6.4"
+    "typescript": "^4.6.4"  //  <-- added a caret
```

and tests started passing.

Does this change break anything?

**Comment by Shurtu-gal** [comment]
> Does this change break anything?

It should not as `^` is used for backward compatible releases.

**Comment by aeworxet** [comment]
Asked just in case. It might had been hard-locked on that version for a reason. :shrug:

**Review by Shurtu-gal — APPROVED** [review]
LGTM

**Pull request merged**
