### PR TITLE
feat: change the collectionType for arrays for C# models

### LINKED ISSUE #469: Change the collection type for arrays for C# models
#### Reason/Context
In Modelina for C#, you can change the type used for representing arrays, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpArrayType` as an enum that can contain two values `List` or `Array`, where `Array` is the default. It should be added to the generator options as following:
```  
  collectionType: 'List'
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-change-collection-type/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-change-collection-type/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#change-the-collection-type-for-arrays

Feel free to reach out if you have any questions or get stuck!

### PR DESCRIPTION
**Pull request by prayutsu**
**Description**

- Add `csharpArrayType` flag to pass collection type for C# models.
- Added test case for the same.
**Related issue(s)**

Fixes #469

### CODE REVIEW

**Comment by prayutsu** [comment]
@jonaslagoni Please take a look

**Review by jonaslagoni — DISMISSED** [review]
LGTM 👍 

Nice @prayutsu 🚀

**Comment by prayutsu** [comment]
@Souvikns @magicmatatjahu @derberg @boyney123 PTAL and also approve the workflow

**Comment by prayutsu** [comment]
@jonaslagoni Is there any linter configured for the repository?

**Comment by prayutsu** [comment]
@derberg This is the same error that I am getting on my local when I use node 14.

**Comment by derberg** [comment]
@prayutsu https://github.com/asyncapi/cli/pull/484 should fix most of issues with tests, including issues you had in your local env.

**Review by derberg — APPROVED** [review]

**Pull request merged**
