### PR TITLE
chore: updating codeowners

### PR DESCRIPTION
**Pull request by boyney123**
**Description**

I would like to be able to review and merge commits into the CLI to help out.

Let me know what you think.

### CODE REVIEW

**Review by magicmatatjahu — APPROVED** [review]
LGTM! Please wait for at least one other approve (btw. Fran isn't in codeowners) :)

**Comment by fmvilas** [comment]
Yeah, as @magicmatatjahu said I'm not a code owner so I'm removing myself from reviewers and adding @jotamusik. Leave it up to you folks!

**Review by Souvikns — APPROVED** [review]
LGTM 🚀

**Comment by derberg** [comment]
@magicmatatjahu please next time wait for other code owners approval. Especially that I wanted to suggest that first would be good to see @boyney123 involvement in the PR review (there are some pending)

**Comment by magicmatatjahu** [comment]
@derberg Souvik also accepted, but sure, next time I will wait for all.

**Comment by derberg** [comment]
yes I saw that, but there was also me and @jotamusik. IMHO it must be a decision of all codeowners as for now approval from just one owner is enough to get PR merged

**Pull request merged**
