### PR TITLE
chore(ci): change pages to markdown

### PR DESCRIPTION
**Pull request by Shurtu-gal**
See https://github.com/asyncapi/website/pull/2938

### CODE REVIEW

**Review by Amzani — APPROVED** [review]
LGTM

**Comment by akshatnema** [comment]
@Shurtu-gal Why we merged this PR in CLI? We haven't updated the migrated website in the repo yet.

**Comment by Shurtu-gal** [comment]
Sorry, had added the `do-not-merge` label and then removed it. Will be reverting it.

**Pull request merged**
