### PR TITLE
docs: fix missing toc

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**

For some reason, the TOC is not generated in README.md. Just manually creating it in this PR.

### CODE REVIEW

**Comment by magicmatatjahu** [comment]
@Souvikns Did you run manually `generate:markdown:toc`? I think that we have some problem on the workflow side and we should try to make it by merging PR.

**Comment by Souvikns** [comment]
> @Souvikns Did you run manually `generate:markdown:toc`? I think that we have some problem on the workflow side and we should try to make it by merging PR.

Yeah, I just ran the command and pushed I figured something was with the workflow because we have a workflow command for this, but was not able to find it out.

**Comment by magicmatatjahu** [comment]
@Souvikns Yeah we have that here https://github.com/asyncapi/cli/blob/master/.github/workflows/if-nodejs-version-bump.yml#L31 I also wonder why it didn't run on the post release workflow 🤔  I can accept that changes because I don't think so that we should wait for that, but please rerun again the markdown-toc generation because maybe there are some changes in the master and ping me, ok? :)

**Comment by Souvikns** [comment]
@magicmatatjahu I just rerun and there aren't any new changes and the branch is up to date with upstream/master

**Review by magicmatatjahu — APPROVED** [review]

**Pull request merged**
