### PR TITLE
feat: support for postman-collection conversion to asyncapi

### LINKED ISSUE #1516: Add convert to AsyncAPI from Postman collection support
As the PR was just merged, it's now possible to convert Postman collection to AsyncAPI v3, and it should be possible to do this through the CLI. Checkout https://github.com/asyncapi/converter-js?tab=readme-ov-file#postman-collection-to-asyncapi-conversion for how to do it.

https://github.com/asyncapi/converter-js/pull/276

### PR DESCRIPTION
**Pull request by Gmin2**
**Description**

Completed the support for conversion of postman collection to asyncapi

**Related issue(s)**
Fixes #1516 

Screenshot from 2024-09-23 23-21-58

Screenshot from 2024-09-23 23-25-34

### CODE REVIEW

**Comment by Gmin2** [comment]
[asyncapi/converter-js#284](https://github.com/asyncapi/converter-js/pull/284) needs to be merged

**Review by Shurtu-gal — APPROVED** [review]
LGTM

**Review by Souvikns — APPROVED** [review]
LGTM 🚀

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Pull request merged**
