### PR TITLE
feat!: generate models for v3 through Modelina CLI

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**

This PR enables https://github.com/asyncapi/cli/issues/883 to generate models through Modelina CLI and replaces https://github.com/asyncapi/cli/pull/1155.

**Related issue(s)**
Fixes https://github.com/asyncapi/cli/pull/1376
Blocked by https://github.com/asyncapi/cli/pull/1228
Blocked by https://github.com/asyncapi/modelina/pull/1952
Blocked by https://github.com/asyncapi/modelina/pull/2008
Blocked by https://github.com/asyncapi/modelina/pull/2010
Blocked by https://github.com/asyncapi/modelina/pull/2009

### CODE REVIEW

**Comment by Amzani** [comment]
@devilkiller-ag https://github.com/asyncapi/cli/pull/1228 is ready for review and should unblock your PR

**Comment by devilkiller-ag** [comment]
Thanks @Amzani. @jonaslagoni, what's your thought on this? Both the PRs that were blocking this have been merged.

**Comment by jonaslagoni** [comment]
Gonna fix this on Tuesday :v:

**Review by Amzani — APPROVED** [review]
LGTM :>

**Comment by Amzani** [comment]
@jonaslagoni some tests are failing
Also what happens to current changes in generate models: (e.g https://github.com/asyncapi/cli/pull/1437)
Do you ensure that they got integrated in modelina-cli ?

**Comment by jonaslagoni** [comment]
> Do you ensure that they got integrated in modelina-cli ?

Depends on what comes first, if that PR is merged before this I will update this PR, if it's the other way around we just release a new version of Modelina CLI 🙂

**Comment by black-snow** [comment]
This will enable us to generate models for asyncapi v3, right? Any ETA?

**Comment by jonaslagoni** [comment]
> This will enable us to generate models for asyncapi v3, right? Any ETA?

ASAP 🙂

**Comment by jonaslagoni** [comment]
@Amzani should have solved all the problems now 😅

**Comment by black-snow** [comment]
> ASAP 🙂

My favourite flavour! ASAP with sprinkles of awesome job, man!

**Review by Amzani — APPROVED** [review]
LGTM

**Comment by jonaslagoni** [comment]
Let me quickly fix a bug in Modelina that prohibits model generation 🤨 Should be done today but lets see

**Review by Shurtu-gal — DISMISSED** [review]
LGTM

**Review by Amzani — APPROVED** [review]
LGTM 🚀

**Pull request merged**
