### PR TITLE
test: handle a different analytics config file for testing

### PR DESCRIPTION
**Pull request by peter-rr**
This PR will allow to set up the env var `ASYNCAPI_METRICS_CONFIG_PATH` to a known and controlled config file path instead of using the one located in ~home.

Relates to #1427

### CODE REVIEW

**Comment by peter-rr** [comment]
@Shurtu-gal Yeah, the failing test should pass when https://github.com/asyncapi/cli/pull/1451 is merged.

**Comment by peter-rr** [comment]
@Shurtu-gal Tests are passing now. PR ready for review 👍

**Review by Souvikns — APPROVED** [review]

**Review by Amzani — APPROVED** [review]
LGTM

**Pull request merged**
