### PR TITLE
chore: remove @jotamusik from codeowners

### PR DESCRIPTION
**Pull request by jotamusik**
**Description**
As I'm not able to spend any time on open source right now, I think it's not fair to appear as codeowner right now, so I'm deleting myself. Hope to colaborate again on the future and keep being such a great community! 🤗

### CODE REVIEW

**Comment by derberg** [comment]
Thanks man for the time spent here with us. It was a pleasure!

**Review by derberg — APPROVED** [review]

**Review by magicmatatjahu — APPROVED** [review]
😢  Take care, and come back soon!

**Review by Souvikns — APPROVED** [review]
Thanks for helping me when I was new to the project.

**Pull request merged**
