### PR TITLE
feat: add Glee tutorial template

### PR DESCRIPTION
**Pull request by fmvilas**
**Description**

It adds the `--template` (`-t`) option to the `asyncapi new glee` and `asyncapi new project` commands. It let's you choose which template to use to generate the Glee project.

I'm also providing a new template to use for the Code Generation tutorial we'll have on the website after releasing v3.

##### TODO
- [x] Upgrade `package.json` of each template so they use the latest Glee release.

### CODE REVIEW

**Review by Souvikns — APPROVED** [review]
Both `asyncapi new glee` and `asyncapi new project` create a glee project, still should we have both commands, doesn't it create confusion?

**Comment by derberg** [comment]
`asyncapi new project` can definitely be removed

as if it comes to the requirements for this PR, the template from this PR is not implementing req/reply so why waiting for new glee features?

**Comment by fmvilas** [comment]
> as if it comes to the requirements for this PR, the template from this PR is not implementing req/reply so why waiting for new glee features?

That's definitely not needed. I removed it. I was experiencing an error that I thought it was caused by the req/reply PR but was actually caused by https://github.com/asyncapi/glee/pull/589.

**Comment by fmvilas** [comment]
Regarding `asyncapi new project`, I created this issue: https://github.com/asyncapi/cli/issues/913.

**Review by derberg — APPROVED** [review]

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
