### PR TITLE
feat: added openapi conversion support

### PR DESCRIPTION
**Pull request by Gmin2**
**Description**

In convert command added support for converting openapi to asyncapi and also introduced a `-p` flag for `perspective` for this conversion

image

**Related issue(s)**
#1498

### CODE REVIEW

**Comment by Gmin2** [comment]
This can only be merged when [asyncapi/converterjs#284](https://github.com/asyncapi/converter-js/pull/274)

**Comment by Shurtu-gal** [comment]
@Gmin2 could you check the issue with tests?

**Comment by Gmin2** [comment]
> @Gmin2 could you check the issue with tests?

Done @Shurtu-gal just need to wait for [asyncapi/converter-js#280](https://github.com/asyncapi/converter-js/pull/280) to be merged

**Review by Souvikns — APPROVED** [review]
LGTM 🚀

**Pull request merged**
