### PR TITLE
feat: format command to convert asyncapi document to multiple format

### PR DESCRIPTION
**Pull request by catosaurusrex2003**
**Description**
Added a new format command.
used [js-yaml](https://www.npmjs.com/package/js-yaml) which was already a dependency.

-f flag defines the output format.
if -o flag is provided writes output to a file, else logs in the console.
image

Corner case checks
image

Help
image

**Related issue(s)**
#1535

### CODE REVIEW

**Comment by catosaurusrex2003** [comment]
should the tests be included in this PR or i create another one.

**Comment by Souvikns** [comment]
@catosaurusrex2003 you have some lint issues, can you have a look.

**Comment by catosaurusrex2003** [comment]
@Souvikns fixed

**Comment by catosaurusrex2003** [comment]
@Souvikns is something else required in this ?

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
