### PR TITLE
feat: generate auto-implemented properties for C# models 

### LINKED ISSUE #468: Generate auto-implemented properties for C# models
#### Reason/Context
In Modelina for C#, you can make it generate the models with auto-implemented properties, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpAutoImplement` as a boolean. If true the generator should include the following options:
```  
  presets: [
    {
      preset: CSHARP_DEFAULT_PRESET,
      options: {
        autoImplementedProperties: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-auto-implemented-properties/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-auto-implemented-properties/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-auto-implemented-properties

Feel free to reach out if you have any questions or get stuck!

### PR DESCRIPTION
**Pull request by prayutsu**
**Description**

- Added `csharpAutoImplement` flag to generate auto-implemented properties for C# models
**Related issue(s)**

Fixes #468

### CODE REVIEW

**Review by jonaslagoni — DISMISSED** [review]
LGTM 👍

**Comment by prayutsu** [comment]
@Souvikns @magicmatatjahu  @derberg @boyney123  PTAL

**Comment by derberg** [comment]
@prayutsu hey, you need to solve some conflicts

**Comment by prayutsu** [comment]
> @prayutsu hey, you need to solve some conflicts

Done

**Review by derberg — APPROVED** [review]

**Pull request merged**
