### PR TITLE
setting up commands

### PR DESCRIPTION
**Pull request by Souvikns**
---
> Still not complete figuring out all the commands
---

**Description**

- Just installed commander and had set it up

**Related issue(s)**
#1

### CODE REVIEW

**Comment by GouravSardana** [comment]
@jonaslagoni can we add codacy checks here for code quality ?
+ Add sonar cloud bot too. It will be easy for us to maintain the code quality from starting ;)

**Comment by jonaslagoni** [comment]
> @jonaslagoni can we add codacy checks here for code quality ?
> 
>     * Add sonar cloud bot too. It will be easy for us to maintain the code quality from starting ;)

We can yes, I would suggest you add a linter as well from the start - similar to https://github.com/asyncapi/parser-js/blob/2b1d06fef5600caf4893638c58b568fe8d71ced4/package.json#L19, we learned it the hard way and had to refactor a bunch 😄. I will add a PR for the GitHub actions.

**Comment by derberg** [comment]
yes, eslint for static code analysis, 
sonar cloud enabled just now

**Comment by derberg** [comment]
@Souvikns we do not want to use commander but https://github.com/vadimdemedes/ink, we use commander in current generator CLI, but want better user experience that Ink can bring. @jotamusik is working on introducing it.

@jotamusik looking at the interest from the community, maybe you could already open a PR, even if not yet ready, folks that want to help could already jump in and provide feedback, what do you think?

**Comment by Souvikns** [comment]
@derberg ok so let me read [ink](https://github.com/vadimdemedes/ink) and then can update the pr.

**Comment by jotamusik** [comment]
>@jotamusik looking at the interest from the community, maybe you could already open a PR, even if not yet ready, folks that want to help could already jump in and provide feedback, what do you think?
Okey! I will do it this afternoon! :P

**Pull request closed without merging**
