### PR TITLE
feat: create new command to format the asyncapi document

### PR DESCRIPTION
**Pull request by AayushSaini101**
Closes: #1419 
Related: #1508 
* Added new command  to format the Asyncapi document [ Done ] [ json, yaml support ]
*  Test cases to verify the command [ Done Added test cases]

### CODE REVIEW

**Comment by AayushSaini101** [comment]
@Souvikns a new command has already introduced https://github.com/asyncapi/cli/pull/1549 via this MR, that is asyncapi format that change one format to another format.  I think we can use asyncapi pretty <asyncapi.yml> command to format the asyncapi document

**Comment by AayushSaini101** [comment]
> Thanks for the name change @AayushSaini101
> 
> Is adding a JSON AsyncAPI document prettifier also within the scope of this pr?

Added json support also @catosaurusrex2003  thanks : )

**Review by Souvikns — APPROVED** [review]
LGTM 🚀

**Pull request merged**
