### PR TITLE
feat: integrate asyncapi optimize library using the optimize command

### LINKED ISSUE #218: Add `asyncapi optimize` command
> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

#### Reason/Context

We need to enable the community to use all AsyncAPI tools in CLI if only possible -> https://github.com/asyncapi/optimizer

#### Description

- add new command `asyncapi optimize` that uses https://github.com/asyncapi/optimizer and enable users to optimize single AsyncAPI file
- user should be able to pass one files to the optimizer `asyncapi optimize <context/filepath/url>` (getting file from context or filepath or URL is already provided in  CLI, you just use `load` function)
- by default it would optimize the document and print to the terminal, but user should be able to specify to get only the report, with flag `--report`
- by default full optimization is done, but user should be able to specify `--rules` where user can provide rules that should be applied by optimizer

> This issue is for https://www.openforce.tech/ participants. If you do not participate in this even please pick up other issue from this repo, there is plenty of help needed 😄 

@KhudaDad414 pinging you so you are aware 😄

### PR DESCRIPTION
**Pull request by alceil**
**Description**

This PR integrates the [asyncapi-optimize](https://github.com/asyncapi/optimizer) library using the optimize command.

At the moment, the command looks something like this.

`asyncapi optimize <context/filepath/url>`

And it has flag:
--format which determines the show the report or not.

**Related issue(s)**
Fixes #218

### CODE REVIEW

**Comment by KhudaDad414** [comment]
Thanks, @alceil looks great.
just some inputs from my side:

when I use the optimize command, I expect it to show me the changes that are going to be applied and I should be able to chose between those changes.

this is the flow that I expect to go through:
```
# asyncapi optimize document.yml
Here is a list of optimizations that can be done on document.yml:

Remove the following components:
 - components.messages.foo
 - components.schemas.bar
...
 
Reuse the following components:
 - components.schemas.foo in channels.someMessge.publish.message.payload
 - components.schemas.bar in channels.someMessge.publish.message.payload
...

Move the following components to the components section:
 - channels.foo.publish.message to channels.someMessge.publish.message.payload
 - channels.foo.subscribe.headers[0] to components.schemas.schema_1
...

Select your desired optimization to be applied:
   Delete Components
   Remove Components
   Reuse Components
> All of them

select your desired output:
   Update the current file
> Create document_optimized.yml (Recommended)
   Log to console

document_optimized.yml has been created!
```
we definitely need some input about the UX from others here.
cc: @derberg @magicmatatjahu @Souvikns

**Comment by alceil** [comment]
Can I also get some inputs on the Ux as well. @KhudaDad414 . Im pretty new to this so I need some pointers as well on how to approach it

**Comment by derberg** [comment]
from the UX perspective we need to support 2 ways of doing things:
- interactivity, step by step guiding user. As shown by @KhudaDad414, that you show what can be optimized and user can select what changes should be applied
- flags to skip interactivity in case CLI is used on a CI/CD. So user should be able to specify with flags desired out come + should be powered by defaults. So for example, default should be that if `--no-tty` is passed document is optimized, but the result is logged to terminal, and you can as alternative specify `--override` or `--output` flags to save optimized document into file. 

does it make sense?

**Comment by alceil** [comment]
Okay got it @derberg

**Comment by derberg** [comment]
@alceil do you plan to continue working on it? Open Force ended but since you started during the event, it is ok if you complete work later

**Comment by alceil** [comment]
Sure i wish to complete it .

**Comment by imabp** [comment]
>Can I also get some inputs on the Ux as well. @KhudaDad414 . Im pretty new to this so I need some pointers as well on how to approach it

@alceil for UX, we are following [CLIG](https://clig.dev), as mentioned in readme.

As @KhudaDad414  mentioned, @alceil . I guess you are working on it, feel free if you feeling stuck anywhere. An idea that you can think for the implementation is using a `stepper` design.

1. First step is to just look on the optimizations possible and show users a list of possible optimizations in tabular format(more readable way).

2. Second step is to  let the user choose from the given four options, `reuse`, `remove`, `move`, and `All of them`

3. Third step is to ask the updated file preferences with these options 
` Update the current file`, `Create document_optimized.yml (Recommended)`
 and `Log to console`

**Comment by derberg** [comment]
@alceil hey, this PR is opened for some time already, maybe we should close and you create new when ready?

**Comment by KhudaDad414** [comment]
I am putting it on my to-do list. thanks for reminding @derberg.

**Comment by KhudaDad414** [comment]
I guess we should close this PR in favour of https://github.com/asyncapi/cli/pull/397

**Comment by derberg** [comment]
closing since @alceil is no longer active here and @KhudaDad414 opened new PR

**Pull request closed without merging**
