### PR TITLE
feat: add `tsIncludeComments` flag in generate command for typescript lang

### LINKED ISSUE #463: Generate documentation with example for TypeScript models
#### Reason/Context
In Modelina for TypeScript, you can make it generate the models with documentation and examples for properties and classes/interfaces, this should be possible through the CLI.

To do this I suggest we add a flag called `tsIncludeComments` as a boolean. If true the generator should include the following options:
```
  presets: [TS_DESCRIPTION_PRESET]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L118 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-comments/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-comments/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L39

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#rendering-comments-from-description-and-example-fields

Feel free to reach out if you have any questions or get stuck!

### PR DESCRIPTION
**Pull request by Manish3323**
**Description**
Adds `tsIncludeComments` flag in generate command for typescript language.

**Related issue(s)**
Fixes #463

### CODE REVIEW

**Review by jonaslagoni — APPROVED** [review]
LGTM 👍

**Comment by derberg** [comment]
@Manish3323 can you solve merge conflicts 🙏🏼

**Comment by Manish3323** [comment]
@derberg done.. do have a look at it again.

**Comment by derberg** [comment]
sorry @Manish3323 another conflict there

**Comment by Manish3323** [comment]
@derberg rebased

**Comment by Manish3323** [comment]
@derberg waiting for approval.

**Review by derberg — APPROVED** [review]

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request closed without merging**
