### PR TITLE
fix: switch from mocha and chai to the jest

### PR DESCRIPTION
**Pull request by magicmatatjahu**
**Description**

- switch from `mocha` and `chai` to the `jest`. Simple reason. Mocha and chai (specifically, a `ts-node` which transpiles code from TS to JS) has a some problems with importing ESM. I found that problems when I started writing tests for https://github.com/asyncapi/cli/pull/347 and new parser uses new module syntaxes. We still need `chai` in devDependencies, because `@oclif/test` uses it underneath.
- bump `@oclif/core` to the latest `^1.18.0` version.

**Related issue(s)**
See more https://github.com/asyncapi/cli/pull/347

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
sorry but let us first merge https://github.com/asyncapi/cli/pull/221

**Comment by magicmatatjahu** [comment]
@derberg Done, could you check again? :)

**Comment by magicmatatjahu** [comment]
@derberg ping, ping :P

**Review by derberg — COMMENTED** [review]
can you share why changes in `[src/base.ts](https://github.com/asyncapi/cli/pull/353/files#diff-440b55a9ff9e0486020fc49197f3278d14446306fc0c5d5107b48139c20bfda6)` were needed? and also is oclif upgrade necessary, related to refactoring of tests?

**Review by derberg — APPROVED** [review]
lgtm, but because prod dependency got updated, we should release it as `fix: ` and indicate it clearly in the description that it is not only refactor of tests really, but core dependency got also upgraded.

I approve but please make sure to make proper adjustments before merge

**Review by derberg — APPROVED** [review]

**Pull request merged**
