### PR TITLE
feat: add csharp newtonsoft based model generation support

### LINKED ISSUE #464: Generate Newtonsoft support for C# models
#### Reason/Context
In Modelina for C#, you can make it generate the models with Newtonsoft serialization support, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpNewtonsoft` as a boolean. If true the generator should include the following options:
```
  presets: [CSHARP_NEWTONSOFT_SERIALIZER_PRESET]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-newtonsoft-serializer/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-newtonsoft-serializer/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#using-newtonsoftjsonnet

Feel free to reach out if you have any questions or get stuck!

### PR DESCRIPTION
**Pull request by kaushik-rishi**
**Description**
- add's newtonsoft based model generation support for csharp

**Related issue(s)**
Fixes #464

### CODE REVIEW

**Review by derberg — DISMISSED** [review]
@jonaslagoni wanna have a look before we merge?

if all good you can trigger merge

**Comment by jonaslagoni** [comment]
Well, after the merge 😄

**Review by derberg — APPROVED** [review]

**Comment by kaushik-rishi** [comment]
> @kaushik-rishi you have some conflicts to solve

resolved.

**Comment by kaushik-rishi** [comment]
https://github.com/asyncapi/cli/actions/runs/5067480616/jobs/9098588250 

Is this failing due to this PR merge ? @jonaslagoni @derberg

**Comment by derberg** [comment]
@kaushik-rishi don't worry these random timeouts happen

**Pull request merged**
