### PR TITLE
feat: add hashcode and equals flags for csharp code generation

### LINKED ISSUE #467: Generate overwritten GetHashCode method for C# models
#### Reason/Context
In Modelina for C#, you can make it generate the models with the GetHashCode method overwritten, this should be possible through the CLI.

To do this I suggest we add a flag called `csharpHashcode` as a boolean. If true the generator should include the following options:
```  
presets: [
    {
      preset: CSHARP_COMMON_PRESET,
      options: {
        hashCode: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L137 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-equals-and-hashcode/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/csharp-generate-json-serializer/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L95

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/Csharp.md#generate-models-with-equals-and-gethashcode-methods

Feel free to reach out if you have any questions or get stuck!

Related issue https://github.com/asyncapi/cli/issues/466

### PR DESCRIPTION
**Pull request by kaushik-rishi**
**Description**
- adds `csharpHashcode` and `csharpEquals` flags.

**Related issue(s)**
- Fixes #467 and #466

### CODE REVIEW

**Comment by kaushik-rishi** [comment]
@jonaslagoni 

I've added test for `hashcode` flag and `equal` flag alone, should i also add a test when both the flags are passed ?

**Review by jonaslagoni — APPROVED** [review]
Its definitely not a bad test to have, but don't think it's required 🙂 

Nice job 👍

**Comment by jonaslagoni** [comment]
@kaushik-rishi in the CLI repo or?

**Comment by kaushik-rishi** [comment]
> @kaushik-rishi in the CLI repo or?

Open for issues in other repositories as well :smile:

**Comment by jonaslagoni** [comment]
I dont have anything specific in mind 😄 

My best suggestion is to:

- find a repo you wish to contribute to, or a library you find interesting
- see if any issue sounds interesting
  - if the issue is not that well described or you have no idea where to begin, ping the maintainers for some clarification
- play around with the library and make your own suggestions for improvements

**Review by derberg — APPROVED** [review]

**Pull request merged**
