### PR TITLE
feat: add `tsExampleInstance` flag and test for generate models 

### LINKED ISSUE #462: Generate example function for TypeScript models
#### Reason/Context
In Modelina for TypeScript, you can make it generate the models generate functions that return a basic instance example, this should be possible through the CLI.

To do this I suggest we add a flag called `tsExampleInstance` as a boolean. If true the generator should include the following options:
```
  presets: [
    {
      preset: TS_COMMON_PRESET,
      options: {
        example: true
      }
    }
  ]
```
Which should be added here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/src/commands/generate/models.ts#L118 as the code example shows: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-jsonbinpack/index.ts

These will be the generated results: https://github.com/asyncapi/modelina/blob/master/examples/typescript-generate-example/__snapshots__/index.spec.ts.snap

Remember to also add a test here: https://github.com/asyncapi/cli/blob/438de0741e9ef29672b6e3af483b90e796903a7d/test/commands/generate/models.test.ts#L39

Related documentation: https://github.com/asyncapi/modelina/blob/master/docs/languages/TypeScript.md#generate-example-data-function

Feel free to reach out if you have any questions or get stuck!

### PR DESCRIPTION
**Pull request by chinma-yyy**
**Description**

- Added `tsexampleInstance` flag which will add the example option to the model
- Created an `options` object which can be reused and declared once based on the flags
- Added the relevant test script and updated the Docs

**Related issue(s)**

Resolves #462

### CODE REVIEW

**Comment by chinma-yyy** [comment]
@jonaslagoni  Will need help on the part of description of the flag.

**Comment by chinma-yyy** [comment]
> @jonaslagoni Will need help on the part of description of the flag.

@jonaslagoni !!

**Comment by jonaslagoni** [comment]
@chinma-yyy what do you need help with? 🙂 

Looks fine to me 👍

**Comment by derberg** [comment]
> @jonaslagoni waiting !

@chinma-yyy were you shouting? 😅

**Pull request merged**
