### PR TITLE
feat: adding support to change the collection type for arrays in Java models

### LINKED ISSUE #1436: [FEATURE] Add support to change the collection type for arrays in Java models
### Why do we need this improvement?

In Modelina we can change the default collection type from array to List in Java. The CLI should allow the same.

### How will this change help?

It will allow to generate Java models that implement collections as either arrays or Lists, depending on the configuration.

### Screenshots

_No response_

### How could it be implemented/designed?

Similarly as how the same issue for C# https://github.com/asyncapi/cli/issues/469 was implemented via https://github.com/asyncapi/cli/pull/481, by introducing a new parameter javaArrayType with the possible values being Array (default) and List

### 🚧 Breaking changes

No

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by borrull**
**Description**
This PR adds support to change the collection type in Java models by introducing a new parameter "javaArrayType" to the generate models command.

**Related issue(s)**
Resolves #1436

### CODE REVIEW

**Review by peter-rr — APPROVED** [review]
LGTM 👍

**Comment by Amzani** [comment]
@borrull could you sync with @jonaslagoni as you might conflict with https://github.com/asyncapi/cli/pull/1376
I'm closing this PR for now.

**Comment by jonaslagoni** [comment]
@borrull, do you want me to add your code to https://github.com/asyncapi/modelina/tree/next/modelina-cli or do you want to help make the contribution there?

**Comment by borrull** [comment]
@jonaslagoni if it can wait for 2-3 hours, I can make the contribution there. Otherwise, please go ahead :-)

**Comment by borrull** [comment]
Hi @jonaslagoni . delayed but there it is, please check it out https://github.com/asyncapi/modelina/pull/2029

**Pull request closed without merging**
