### PR TITLE
feat: add support for modelina in v3

### PR DESCRIPTION
**Pull request by fmvilas**
Activate support for v3 in asyncapi generate models 😄

### CODE REVIEW

**Comment by KhudaDad414** [comment]
@fmvilas never thought it could be this easy to support something... 😆

**Review by derberg — CHANGES_REQUESTED** [review]
wait, did you just want to merge without approval?

what about tests adjustment, so we know v3 really works?

**Review by Souvikns — APPROVED** [review]

**Comment by fmvilas** [comment]
Not trying to merge without approval @derberg. Just leaving it there for when you approve it merges automatically.

**Comment by derberg** [comment]
but we should not remove unnecessary test but have an update to the test to make sure v3 works

> Not trying to merge without approval @derberg. Just leaving it there for when you approve it merges automatically.

but that is not how things work with ready to merge. Once you push any small change, it is no longer ready to merge and label is anyway removed

**Review by jonaslagoni — COMMENTED** [review]
In order to enable AsyncAPI v3 for Modelina you need to switch to the next branch. 

This does contain breaking changes for the models, as well as not being fully released more might pop up.

**Comment by jonaslagoni** [comment]
@fmvilas you can bump the version to v3 now, that supports AsyncAPI v3 and is stable ✌️

**Comment by derberg** [comment]
closing in favour of https://github.com/asyncapi/cli/pull/1155

**Pull request closed without merging**
