### PR TITLE
chore: added ui/ux improvements in optimize commands 

### LINKED ISSUE #1383: Implement new UI/UX improvements in optimize command
Related to #1214

### PR DESCRIPTION
**Pull request by Vishalk91-4**
**Description**

- Added UI Functionality Chnges in the Optimize Command
- image
- image
- image

**Related issue(s)**
Resolves #1383

### CODE REVIEW

**Comment by Souvikns** [comment]
Hi @Vishalk91-4 thanks for opening this PR, can you update the PR title following https://www.conventionalcommits.org/en/v1.0.0/.

**Comment by Vishalk91-4** [comment]
> Hi @Vishalk91-4 thanks for opening this PR, can you update the PR title following https://www.conventionalcommits.org/en/v1.0.0/.

@Souvikns Made the Changes, PTAL

**Comment by Souvikns** [comment]
@Vishalk91-4 you have some tests failing, just update the tests according to the changes that you are introducing.

**Comment by Vishalk91-4** [comment]
> @Vishalk91-4 you have some tests failing, just update the tests according to the changes that you are introducing.

Fixed those errors

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
