### PR TITLE
fix: resolved faulty spinner loading after error in console

### LINKED ISSUE #1607: [BUG] "generate models java" without packageName hangs
### Describe the bug.

Running `asyncapi generate models java foo.yml`, without the required `--packageName` argument correctly prints an error, but then the cli incorrectly indicates it is still generating models, but hangs (until killed, e.g. with ctrl-C).

### Expected behavior

Print an error and exit

### Screenshots

```
Error: In order to generate models to Java, we need to know which package they are under. Add `--packageName=PACKAGENAME` to set the desired package name.
◒  Generating models...
```

### How to Reproduce

 Run `asyncapi generate models java foo.yml`

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by SahilDahekar**
**Description**

- Added a try catch to stop spinner if `Error` is throw by `generateModels()` func.

**Related issue(s)**

Resolves #1607

### CODE REVIEW

**Comment by SahilDahekar** [comment]
Although this particular bug is fixed by adding try catch block ,  I am not very confident in the implementation and working of this command because i tried using interactive mode and it didn't work as it should .

**Comment by Souvikns** [comment]
@SahilDahekar can you attach some images of the error, and solution hard to understand what is happening.

**Comment by SahilDahekar** [comment]
@Souvikns 

### **Before :**

The Generating models spinner does not stop even after error. 

Screenshot from 2024-12-29 12-43-33


In order to stop have to manually cancel the operation.

Screenshot from 2024-12-29 12-43-43

### **After :** 

No longer have faulty spinner and error logged to console.

Screenshot from 2024-12-29 12-42-36

**Review by Souvikns — APPROVED** [review]
LGTM 🚀

**Pull request merged**
