### PR TITLE
ci: fix assets generation on windows machines

### LINKED ISSUE #1349: [BUG] Release pipeline is blocked by the windows cache issue
### Describe the bug.

The release pipeline is blocked because of [a bug in the npm CLI](https://github.com/npm/cli/issues/7308).

All of the PRs are currently blocked and can't be merged.
https://github.com/asyncapi/cli/actions/runs/8603295012/job/23574862323

### Expected behavior

It shouldn't be blocked.

### Screenshots

..

### How to Reproduce

..

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

### PR DESCRIPTION
**Pull request by helios2003**
**Description**
The build process passes the entire ``Test NodeJS PR`` pipeline. 

**Related issue(s)**

Fixes #1349

### CODE REVIEW

**Comment by helios2003** [comment]
Maintainers, as mentioned in the issue, I tried fixing the caching issue on Windows machines by conditionally checking the ``npm cache``. But a certain substep is failing which passes on other machines. It would be great if someone could point me in the right direction about what is going wrong. 

**Fix till now:**
image

**Failed subprocess**
image

Link to the workflow: https://github.com/helios2003/cli/actions/runs/8624914219/job/23640659229?pr=1

**Comment by Souvikns** [comment]
I think it is fixed @helios2003 with https://github.com/asyncapi/cli/pull/1340

**Comment by helios2003** [comment]
I tried running the earlier workflow and apparently, it doesn't pass the same subprocess and also it fails the macOS workflow. 
Link: https://github.com/helios2003/cli/actions/runs/8626561222/job/23644917594?pr=2

**Comment by Souvikns** [comment]
> Hi @Souvikns, thanks for the quick reply. I tried running the earlier workflow and apparently, it doesn't pass the same subprocess and also it fails the macOS workflow. Link: https://github.com/helios2003/cli/actions/runs/8626561222/job/23644917594?pr=2


Yeah, I saw this in other PRs as well, does not look like it is occurring due to cache though.

**Comment by helios2003** [comment]
Oh okay, so can I try to fix the errors in this https://github.com/helios2003/cli/actions/runs/8626561222/job/23644917594?pr=2

**Comment by derberg** [comment]
@helios2003 it is not caching

it is because one script is still not modified to support windows

just revert your change and update https://github.com/asyncapi/cli/blob/master/package.json#L143 script from `printf` command to below node script

`node -e \"const fs = require('fs'); fs.writeFileSync('scripts/README.md', '# Usage\\n\\n<!-- usage -->\\n\\n# Commands\\n\\n<!-- commands -->\\n');\"`

**Review by derberg — APPROVED** [review]

**Pull request merged**
