### PR TITLE
fix: exit with 1 for failing validations

### LINKED ISSUE #861: fail-severity warn info
#### Describe the bug
The fail-severity doesn't generate an exit code 1 even for the warn/info severity.  
@asyncapi/cli/0.58.12 linux-x64 node-v18.16.0

#### How to Reproduce
`asyncapi validate schema.yaml --fail-severity=warn`
image
`echo $?`
`0`

#### Expected behavior
The exit code should be `1` but got `0`.

### PR DESCRIPTION
**Pull request by JarnoRFB**
**Description**

Exit the `validate` with 1 for failing validations. Failing validations should exit with code 1 so they can be used in CI and also comply with the commands' documentation.

**Related issue(s)**
Resolves #861

### CODE REVIEW

**Comment by JarnoRFB** [comment]
While the implementation should be straight-forward, the tests somehow fail and report `Error: Expected to exit with code 1 but it ran without exiting`, which I don't see the reason for.

**Comment by JarnoRFB** [comment]
Test are all green locally now, so this would be ready to review.

**Review by Ferror — APPROVED** [review]
I just wanted to open the issue for it and I salute you for fixing it <3

**Comment by JarnoRFB** [comment]
@Souvikns @magicmatatjahu @derberg is there anything I should do to proceed with the PR?

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
