### PR TITLE
refactor: improve error cases in 'scripts/fetch-asyncapi-example.js'

### PR DESCRIPTION
**Pull request by peter-rr**
This PR will refactor 'scripts/fetch-asyncapi-example.js' by adding more detailed and user-friendly error cases and doing also some cleanup.

**Related issue(s)**
Relates to https://github.com/asyncapi/cli/pull/877

### CODE REVIEW

**Comment by peter-rr** [comment]
Conflicts already solved. Ready for review 👍

**Review by Amzani — APPROVED** [review]
LGTM

**Pull request merged**
