### PR TITLE
feat: migrate to latest oclif version

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**
This PR aims to migrate to the new oclif version and also remove other unnecessary packages, and follow the new doc by oclif. 

**Related issue(s)**

See also #192

### CODE REVIEW

**Comment by Souvikns** [comment]
I modeled my PR based on the current boilerplate that oclif generates when we create a new project. packages like `@oclif/command`, `@oclif/config` have been merged into `@oclf/core`. Functionality did not change much just needed to update the imports and that's all. 

Some things changed like 
- Now we can not access `this._help()` to show the command level help. I couldn't find resources to how we can achieve this now. Opened an Issue asking about this https://github.com/oclif/core/issues/360. 
- Now topics are treated separately and https://oclif.io/docs/topics and also has inbuilt support for [topic separators](https://oclif.io/docs/topic_separator) so we don not need third party plugins now.

**Comment by magicmatatjahu** [comment]
@Souvikns Do you want to wait for feedback in https://github.com/oclif/core/issues/360 issue? Also I wonder if we should go with `chore:` prefix because if we merge it and then try to merge another PRs we won't that `help` support, so I guess that we will have inconsistent in the code, right? Sorry I'm not up to date with CLI code, so I don't know.

**Comment by Souvikns** [comment]
> @Souvikns Do you want to wait for feedback in [oclif/core#360](https://github.com/oclif/core/issues/360) issue? Also I wonder if we should go with `chore:` prefix because if we merge it and then try to merge another PRs we won't that `help` support, so I guess that we will have inconsistent in the code, right? Sorry I'm not up to date with CLI code, so I don't know.

I do want to wait for the reply but then again the CLI is showing warnings in production I am kinda confused on what should we do here. 

Also topic help works but the command is slightly changed
**Before** 
`asyncapi start` would show the topic level help 
**Now** 
needs `asyncapi start --help` shows help

**Comment by magicmatatjahu** [comment]
@Souvikns Sorry for that delayed response.

Hmmm 🤔  Ok, I understand. However, I have still that afraid with merging it, because we have a lot opened PRs and even if we merge it as `chore:` and then try to fix problems as fast as possible, other people will have to wait for us. cc @derberg

**Comment by Souvikns** [comment]
Maybe we wait and let others finish and then merge it, that way we don't block anyone.

**Comment by magicmatatjahu** [comment]
@Souvikns 

> Maybe we wait and let others finish and then merge it, that way we don't block anyone.

I prefer that option. Of course we should wait only for some PRs, not for everyone, that PRs which is very close to merge :)

> found a way to show command help for topics all thanks to https://github.com/oclif/core/issues/360 Now everything works like before.

Awesome!

**Comment by Souvikns** [comment]
@magicmatatjahu shall we merge this, https://github.com/asyncapi/cli/issues/244 I think people are having issues. I can help all other PR's with the changes that they might need to do.

**Comment by magicmatatjahu** [comment]
@Souvikns I checked your changes locally and CLI works as expected :) However if we merge it we need focus on fixing problems and release new version in a short time. I can help with opened PRs, but without a release some issues will not be fixed. 

@derberg What do you think?

**Comment by magicmatatjahu** [comment]
@Souvikns Could we merge it as `feat:`? I've already forgotten, but what's stopping us from releasing the new version?

**Comment by Souvikns** [comment]
Once we merge this all other open PRs will have conflict, nothing other than that.

**Comment by derberg** [comment]
we need to release it, not just merge. I recommend `feat: ` prefix

**Comment by magicmatatjahu** [comment]
@Souvikns 

> Once we merge this all other open PRs will have conflict, nothing other than that.

But we can help people to fix their PRs, it's not problem :)

**Comment by derberg** [comment]
@magicmatatjahu did you review it already? do I have to look at something?

**Comment by magicmatatjahu** [comment]
@derberg I checked it locally and it works :) We can merge it.

**Comment by derberg** [comment]
@magicmatatjahu then why didn't you approve it? 😆

**Review by magicmatatjahu — APPROVED** [review]
@derberg I'm waiting for you to make a move 😆 

@Souvikns Awesome work! We should add info the slack that we merge that PR and people should fix their PRs, of course we can help them.

**Pull request merged**
