### PR TITLE
test: change folder structure

### PR DESCRIPTION
**Pull request by Shurtu-gal**
**Description**

- I have made this PR considering that I also have to add unit and integration tests.
- Before, as there were only functionality tests, I put them in the functionality folder.
- These refactoring will help in adding new tests under other categories.

**Related issue(s)**
#599

### CODE REVIEW

**Review by Souvikns — COMMENTED** [review]
I see you have moved the tests to a different folder, can you update the pr comment and talk about why you are making this change and how it will benefit us?

**Comment by Shurtu-gal** [comment]
@Souvikns, I have updated the comment.

**Comment by Shurtu-gal** [comment]
@Souvikns @fmvilas @derberg I have to decide whether I should keep using jest for testing purposes or use mocha for it. I would love your opinions. 

Reasons for not using mocha :- https://github.com/asyncapi/cli/pull/353

Reasons for shifting to mocha:- 
 - It has better support for oclif. Hence gives more accurate coverage

#### With Mocha
image

#### With Jest 
image


Some alternatives can be to mock the commands as functions and test them instead of running them as cli. But I don't have a viable approach for doing so ( Would love your guidance out here 😮‍💨 )

**Comment by chinma-yyy** [comment]
The issue is with the code transpiling. I think we need not shift to mocha instead we can change the collect coverage parameter to live/**/*.js which will collect coverage from the compiled code which will give us the accurate result. Would love to hear on this more. I tried changing the transformer and some config didn't find something useful

**Comment by Shurtu-gal** [comment]
@chinma-yyy Let me also try then 🤖

**Comment by Shurtu-gal** [comment]
> LGTM
> after merging just please go through remaining 10PRs and add comment to the ones that add tests, with info what people have to do to update and follow latest `master`

👍

**Comment by derberg** [comment]
@Souvikns @Shurtu-gal I guess it can be merged? Feel free to do so when ready

**Review by peter-rr — COMMENTED** [review]
LGTM!

**Pull request merged**
