### PR TITLE
fix: update @smoya/asyncapi-adoption-metrics to 2.4.9 version

### PR DESCRIPTION
**Pull request by peter-rr**
This PR will update `@smoya/asyncapi-adoption-metrics` dependency to the latest version.

### CODE REVIEW

**Review by Souvikns — APPROVED** [review]

**Comment by peter-rr** [comment]
Seems like `SonarCloud Code Analysis` workflow is not triggered and that's preventing this PR from being merged. Any clue about it? @Souvikns @Shurtu-gal

**Comment by Souvikns** [comment]
Can you push some minor change here @peter-rr

**Pull request merged**
