### PR TITLE
feat: add checks to verify Extension of files

### PR DESCRIPTION
**Pull request by AayushSaini101**
Close: [Issue 794](https://github.com/asyncapi/cli/issues/794)

### CODE REVIEW

**Comment by AayushSaini101** [comment]
> @AayushSaini101 you have some code smells as per sonarcloud.

@Souvikns Resolved

**Comment by Souvikns** [comment]
Oh linter issue, just run `npm run lint:fix`, which should fix most of the issues. If you still have any other lint issues then try to fix them manually.

**Comment by AayushSaini101** [comment]
> Oh linter issue, just run `npm run lint:fix`, which should fix most of the issues. If you still have any other lint issues then try to fix them manually.

@Souvikns Resolved

**Review by Souvikns — APPROVED** [review]

**Pull request merged**
