### PR TITLE
feat: handle AsyncAPI v3 for diff command

### PR DESCRIPTION
**Pull request by aayushmau5**
**Description**

- Updates diff package to version `0.5.0`
- Handles diff for AsyncAPI v3 documents
- Adds new test for AsyncAPI v3 document and fixes existing tests

**Related issue(s)**

https://github.com/asyncapi/diff/issues/154

### CODE REVIEW

**Comment by aayushmau5** [comment]
@derberg We can close https://github.com/asyncapi/cli/pull/1595 in favour of this PR since it updates the diff package as well

**Review by Shurtu-gal — APPROVED** [review]
LGTM

**Comment by aayushmau5** [comment]
@Shurtu-gal we can add that feature as a TODO and see if there's any way we can implement that feature later :)

**Comment by Shurtu-gal** [comment]
Great.

**Pull request merged**
